site_name: "MeshExpert Live!"
site_url: http://www.datamesh.com
site_description: A Mixed-Reality Show Product.
repo_url: https://github.com/michael2008/ME-Live-Doc
copyright: "Copyright (C) 2016-2017 DataMesh Inc."
docs_dir: docs
theme: 'readthedocs'

pages:
    - ['index.md', 'Home']
    - ['release-notes.md', 'Release Notes']
    - ['getting-started.md', 'Getting Started']
    - ['product-specifications.md', 'Product Specifications']
    - ['user-guide.md', 'User Guide']
    - ['developer-guide.md', 'Developer Guide']
    - ['METoolkit-overview.md', 'METoolkit Developer Manual', 'Overview']
    - ['toolkit/toolkit-man-collaboration-module.md', 'METoolkit Developer Manual', 'Collaboration']
    - ['trouble-shooting.md', 'Trouble Shooting']
    - ['release-history.md', 'Release History']

markdown_extensions:
    - admonition: